package com.zyguo.voicenote.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ITEM_ENTITY".
 */
public class ItemEntity {

    private Long id;
    private Integer userId;
    private String content;
    private String localPath;
    private String url;
    private Boolean isStar;
    private Boolean isVoice;
    private Long createTime;
    private Long remindTime;
    private String type;
    private String column1;
    private String column2;
    private String column3;
    private String column4;
    private String column5;

    public ItemEntity() {
    }

    public ItemEntity(Long id) {
        this.id = id;
    }

    public ItemEntity(Long id, Integer userId, String content, String localPath, String url, Boolean isStar, Boolean isVoice, Long createTime, Long remindTime, String type, String column1, String column2, String column3, String column4, String column5) {
        this.id = id;
        this.userId = userId;
        this.content = content;
        this.localPath = localPath;
        this.url = url;
        this.isStar = isStar;
        this.isVoice = isVoice;
        this.createTime = createTime;
        this.remindTime = remindTime;
        this.type = type;
        this.column1 = column1;
        this.column2 = column2;
        this.column3 = column3;
        this.column4 = column4;
        this.column5 = column5;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getLocalPath() {
        return localPath;
    }

    public void setLocalPath(String localPath) {
        this.localPath = localPath;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Boolean getIsStar() {
        return isStar;
    }

    public void setIsStar(Boolean isStar) {
        this.isStar = isStar;
    }

    public Boolean getIsVoice() {
        return isVoice;
    }

    public void setIsVoice(Boolean isVoice) {
        this.isVoice = isVoice;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getRemindTime() {
        return remindTime;
    }

    public void setRemindTime(Long remindTime) {
        this.remindTime = remindTime;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getColumn1() {
        return column1;
    }

    public void setColumn1(String column1) {
        this.column1 = column1;
    }

    public String getColumn2() {
        return column2;
    }

    public void setColumn2(String column2) {
        this.column2 = column2;
    }

    public String getColumn3() {
        return column3;
    }

    public void setColumn3(String column3) {
        this.column3 = column3;
    }

    public String getColumn4() {
        return column4;
    }

    public void setColumn4(String column4) {
        this.column4 = column4;
    }

    public String getColumn5() {
        return column5;
    }

    public void setColumn5(String column5) {
        this.column5 = column5;
    }

}
