package com.zyguo.voicenote.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.zyguo.voicenote.model.ItemEntity;

import com.zyguo.voicenote.database.ItemEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig itemEntityDaoConfig;

    private final ItemEntityDao itemEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        itemEntityDaoConfig = daoConfigMap.get(ItemEntityDao.class).clone();
        itemEntityDaoConfig.initIdentityScope(type);

        itemEntityDao = new ItemEntityDao(itemEntityDaoConfig, this);

        registerDao(ItemEntity.class, itemEntityDao);
    }
    
    public void clear() {
        itemEntityDaoConfig.getIdentityScope().clear();
    }

    public ItemEntityDao getItemEntityDao() {
        return itemEntityDao;
    }

}
